// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PepperApp.Data;

#nullable disable

namespace PepperApp.Migrations
{
    [DbContext(typeof(PepperContext))]
    [Migration("20230311150648_UpdatedPropertyNames")]
    partial class UpdatedPropertyNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("PepperApp.Entities.Pepper", b =>
                {
                    b.Property<Guid>("PepperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PepperHeatClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("PepperName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PepperScovilleUnitMaximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PepperScovilleUnitMinimum")
                        .HasColumnType("INTEGER");

                    b.HasKey("PepperId");

                    b.ToTable("Peppers");

                    b.HasData(
                        new
                        {
                            PepperId = new Guid("e1aae56b-5acc-4ced-b882-421857453b24"),
                            IsReadOnly = true,
                            PepperHeatClass = "mild",
                            PepperName = "Anaheim",
                            PepperScovilleUnitMaximum = 2500,
                            PepperScovilleUnitMinimum = 500
                        },
                        new
                        {
                            PepperId = new Guid("7c4f423b-db89-4f83-9c44-b09eaa9d025b"),
                            IsReadOnly = true,
                            PepperHeatClass = "mild",
                            PepperName = "Bell Pepper",
                            PepperScovilleUnitMaximum = 0,
                            PepperScovilleUnitMinimum = 0
                        },
                        new
                        {
                            PepperId = new Guid("8fc15408-9a2d-446a-95ee-ac7cf6be023c"),
                            IsReadOnly = true,
                            PepperHeatClass = "super-hot",
                            PepperName = "Carolina Reaper",
                            PepperScovilleUnitMaximum = 2200000,
                            PepperScovilleUnitMinimum = 1400000
                        },
                        new
                        {
                            PepperId = new Guid("ce7772cc-2717-41db-9ea0-5f1fd79567ce"),
                            IsReadOnly = true,
                            PepperHeatClass = "medium-hot",
                            PepperName = "Cayenne",
                            PepperScovilleUnitMaximum = 50000,
                            PepperScovilleUnitMinimum = 30000
                        },
                        new
                        {
                            PepperId = new Guid("fb668cc2-594e-4b9e-8c6a-fca36fb2b868"),
                            IsReadOnly = true,
                            PepperHeatClass = "mild",
                            PepperName = "Banana Pepper",
                            PepperScovilleUnitMaximum = 500,
                            PepperScovilleUnitMinimum = 0
                        },
                        new
                        {
                            PepperId = new Guid("06095ceb-330e-4756-a16e-a3c734ec3150"),
                            IsReadOnly = true,
                            PepperHeatClass = "super-hot",
                            PepperName = "Ghost Pepper",
                            PepperScovilleUnitMaximum = 1100000,
                            PepperScovilleUnitMinimum = 855000
                        },
                        new
                        {
                            PepperId = new Guid("ca569753-34f6-433e-8ec8-589f79f0252f"),
                            IsReadOnly = true,
                            PepperHeatClass = "hot",
                            PepperName = "Habanero",
                            PepperScovilleUnitMaximum = 350000,
                            PepperScovilleUnitMinimum = 100000
                        },
                        new
                        {
                            PepperId = new Guid("08a360d2-06d7-4886-882c-a889dce0328a"),
                            IsReadOnly = true,
                            PepperHeatClass = "medium",
                            PepperName = "Jalapeno",
                            PepperScovilleUnitMaximum = 8000,
                            PepperScovilleUnitMinimum = 2500
                        },
                        new
                        {
                            PepperId = new Guid("9beb9f57-daac-42be-b65e-576207d51960"),
                            IsReadOnly = true,
                            PepperHeatClass = "mild",
                            PepperName = "Poblano",
                            PepperScovilleUnitMaximum = 2000,
                            PepperScovilleUnitMinimum = 1000
                        },
                        new
                        {
                            PepperId = new Guid("250366a0-f451-4bc1-9518-22099707aa05"),
                            IsReadOnly = true,
                            PepperHeatClass = "hot",
                            PepperName = "Scotch Bonnet",
                            PepperScovilleUnitMaximum = 350000,
                            PepperScovilleUnitMinimum = 100000
                        },
                        new
                        {
                            PepperId = new Guid("72db5903-7c97-42b0-8048-9c7a70c5ea77"),
                            IsReadOnly = true,
                            PepperHeatClass = "medium-hot",
                            PepperName = "Serrano",
                            PepperScovilleUnitMaximum = 23000,
                            PepperScovilleUnitMinimum = 10000
                        },
                        new
                        {
                            PepperId = new Guid("0082b608-5266-4b99-af79-1ed4c00ca3ab"),
                            IsReadOnly = true,
                            PepperHeatClass = "medium-hot",
                            PepperName = "Thai Chili",
                            PepperScovilleUnitMaximum = 100000,
                            PepperScovilleUnitMinimum = 50000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
