// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PepperApp.Data;

#nullable disable

namespace PepperApp.Migrations
{
    [DbContext(typeof(PepperContext))]
    [Migration("20230228042344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("PepperApp.Entities.Pepper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PepperHeatClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("PepperName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PepperScovilleUnitMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PepperScovilleUnitMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Peppers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de49b21d-ecdd-4fea-8202-fd44e90c692c"),
                            IsReadOnly = true,
                            PepperHeatClass = "mild",
                            PepperName = "Anaheim",
                            PepperScovilleUnitMax = 2500,
                            PepperScovilleUnitMin = 500
                        },
                        new
                        {
                            Id = new Guid("46f0d70f-ba24-4a61-8e00-ba5288e53f59"),
                            IsReadOnly = true,
                            PepperHeatClass = "mild",
                            PepperName = "Bell Pepper",
                            PepperScovilleUnitMax = 0,
                            PepperScovilleUnitMin = 0
                        },
                        new
                        {
                            Id = new Guid("2c80af23-1ebd-4516-8996-1a4074836365"),
                            IsReadOnly = true,
                            PepperHeatClass = "super-hot",
                            PepperName = "Carolina Reaper",
                            PepperScovilleUnitMax = 2200000,
                            PepperScovilleUnitMin = 1400000
                        },
                        new
                        {
                            Id = new Guid("2b31826c-993b-4a5f-a362-22b184dbbd9f"),
                            IsReadOnly = true,
                            PepperHeatClass = "medium-hot",
                            PepperName = "Cayenne",
                            PepperScovilleUnitMax = 50000,
                            PepperScovilleUnitMin = 30000
                        },
                        new
                        {
                            Id = new Guid("e0712107-4fa9-4891-a157-f52c28e6f513"),
                            IsReadOnly = true,
                            PepperHeatClass = "mild",
                            PepperName = "Banana Pepper",
                            PepperScovilleUnitMax = 500,
                            PepperScovilleUnitMin = 0
                        },
                        new
                        {
                            Id = new Guid("a8e26d11-a9ce-4c36-a146-c16df5639b2e"),
                            IsReadOnly = true,
                            PepperHeatClass = "super-hot",
                            PepperName = "Ghost Pepper",
                            PepperScovilleUnitMax = 1100000,
                            PepperScovilleUnitMin = 855000
                        },
                        new
                        {
                            Id = new Guid("d10c5bc3-f4c0-45e0-872e-6c10266c9940"),
                            IsReadOnly = true,
                            PepperHeatClass = "hot",
                            PepperName = "Habanero",
                            PepperScovilleUnitMax = 350000,
                            PepperScovilleUnitMin = 100000
                        },
                        new
                        {
                            Id = new Guid("d98e4119-4839-4a86-a197-f0579272d93f"),
                            IsReadOnly = true,
                            PepperHeatClass = "medium",
                            PepperName = "Jalapeno",
                            PepperScovilleUnitMax = 8000,
                            PepperScovilleUnitMin = 2500
                        },
                        new
                        {
                            Id = new Guid("edb4ec07-0182-461d-b0ff-757818e3377b"),
                            IsReadOnly = true,
                            PepperHeatClass = "mild",
                            PepperName = "Poblano",
                            PepperScovilleUnitMax = 2000,
                            PepperScovilleUnitMin = 1000
                        },
                        new
                        {
                            Id = new Guid("af7c3106-8847-4b11-adf4-0daea5b73819"),
                            IsReadOnly = true,
                            PepperHeatClass = "hot",
                            PepperName = "Scotch Bonnet",
                            PepperScovilleUnitMax = 350000,
                            PepperScovilleUnitMin = 100000
                        },
                        new
                        {
                            Id = new Guid("435fafff-ecf7-48ce-9a32-147f77a3e983"),
                            IsReadOnly = true,
                            PepperHeatClass = "medium-hot",
                            PepperName = "Serrano",
                            PepperScovilleUnitMax = 23000,
                            PepperScovilleUnitMin = 10000
                        },
                        new
                        {
                            Id = new Guid("135d96a8-29e7-4804-86db-462ab90c11a2"),
                            IsReadOnly = true,
                            PepperHeatClass = "medium-hot",
                            PepperName = "Thai Chili",
                            PepperScovilleUnitMax = 100000,
                            PepperScovilleUnitMin = 50000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
